pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.0.1'
}

rootProject.name = 'errorprone-no-reflection-parent'

include 'errorprone-no-reflection'
include 'errorprone-no-reflection-gradle-plugin'
include 'errorprone-no-reflection-bom'

enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

micronautBuild {
    importMicronautCatalog()
}
